#!/bin/bash
if [ -z "$1" ]
then
    echo "No argument supplied"
    exit 0
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
NAME=$1
FILENAME=$NAME.java
FILEPATH=$DIR/../src/$FILENAME
OUTPUT=$(cat $DIR/../src/Template.java)
OUTPUT=$(echo "$OUTPUT" | sed "s/Template/$NAME/g")
OUTPUT=$(echo "$OUTPUT" | sed "s/INSERT_DATE/$(date)/g")

# add file name for usaco
if [[ $NAME == usaco* ]] ; then
  SUFFIX=$(echo "$NAME" | sed 's/usaco*//' | awk '{print tolower($0)}')
  OUTPUT=$(echo "$OUTPUT" | sed "s/static String file;/static String file = \"$SUFFIX\";/g")
fi

echo "$OUTPUT" > $FILEPATH

echo $FILEPATH
